name: fortnite_api_io
description: An api wrapper for https://fortniteapi.io in dart.
version: 1.0.0
homepage: https://github.com/vanxh/fortnite_api_io
repository: https://github.com/vanxh/fortnite_api_io

environment:
    sdk: ">=2.15.1 <3.0.0"

dependencies:
    dio: ^4.0.4

dev_dependencies:
    lints: ^1.0.0
